version: '3'

networks:
  traefik:
    external:
      name: admin_traefik
  logs:
    external:
      name: admin_logs

services:
  dummy:
    image: ${REGISTRY}/dummy
    networks:
      - traefik
      - logs
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.backend=app"
        - "traefik.frontend.rule=Host:app.${DOMAIN}"
        - "traefik.docker.network=admin_traefik"
      placement:
        constraints:
        - node.role != manager

