global:
  scrape_interval: 15s
  external_labels:
    monitor: 'monitoring'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    scrape_interval: 30s
    dns_sd_configs:
      - names:
          - 'tasks.node_exporter'
        type: 'A'
        port: 9100

  - job_name: 'cadvisor'
    scrape_interval: 30s
    dns_sd_configs:
      - names:
          - 'tasks.cadvisor'
        type: 'A'
        port: 8080

  - job_name: 'traefik'
    scrape_interval: 30s
    dns_sd_configs:
      - names:
          - 'tasks.traefik'
        type: 'A'
        port: 8080
